export const popularProducts = [
  {
    id: 1,
    title: '아이폰 14 Pro 256GB',
    price: '850,000',
    tag: '전자제품',
    timeLeft: '2시간 15분',
    bidCount: 75,
    image: 'https://invalid-url.com/no-image.jpg', // 테스트용 잘못된 URL
    liked: false,
  },
  {
    id: 2,
    title: '맥북 에어 M2 13인치',
    price: '1,200,000',
    tag: '전자제품',
    timeLeft: '5시간 30분',
    bidCount: 42,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 3,
    title: '나이키 에어조던 1 레트로',
    price: '180,000',
    tag: '패션',
    timeLeft: '1일 3시간',
    bidCount: 128,
    image: 'https://broken-image-url.com/fashion.jpg', // 테스트용 잘못된 URL
    liked: false,
  },
  {
    id: 4,
    title: '캐논 EOS R5 미러리스',
    price: '2,800,000',
    tag: '전자제품',
    timeLeft: '3시간 45분',
    bidCount: 23,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 5,
    title: '삼성 갤럭시 S23 Ultra',
    price: '950,000',
    tag: '전자제품',
    timeLeft: '6시간 20분',
    bidCount: 89,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 6,
    title: '에어팟 프로 2세대',
    price: '220,000',
    tag: '전자제품',
    timeLeft: '4시간 10분',
    bidCount: 156,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 7,
    title: '플레이스테이션 5',
    price: '450,000',
    tag: '전자제품',
    timeLeft: '8시간 30분',
    bidCount: 67,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 8,
    title: '아이패드 프로 11인치',
    price: '680,000',
    tag: '전자제품',
    timeLeft: '2일 5시간',
    bidCount: 34,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 9,
    title: '런닝화 아디다스 울트라부스트',
    price: '320,000',
    tag: '스포츠',
    timeLeft: '12시간 45분',
    bidCount: 91,
    image: 'https://no-image-found.com/sports.jpg', // 테스트용 잘못된 URL
    liked: false,
  },
  {
    id: 10,
    title: '원목 테이블 세트',
    price: '280,000',
    tag: '가구',
    timeLeft: '1일 8시간',
    bidCount: 203,
    image: 'https://missing-furniture-image.com/table.jpg', // 테스트용 잘못된 URL
    liked: false,
  },
  {
    id: 11,
    title: '브랜드 핸드백',
    price: '180,000',
    tag: '패션',
    timeLeft: '15시간 20분',
    bidCount: 45,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 12,
    title: '스마트 공기청정기',
    price: '420,000',
    tag: '생활용품',
    timeLeft: '3일 2시간',
    bidCount: 78,
    image: 'https://invalid-home-appliance.com/cleaner.jpg', // 테스트용 잘못된 URL
    liked: false,
  },
  // 추가 상품들 (페이지네이션 테스트용)
  {
    id: 13,
    title: '구찌 시계',
    price: '650,000',
    tag: '패션',
    timeLeft: '7시간 30분',
    bidCount: 112,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 14,
    title: '다이슨 청소기 V15',
    price: '480,000',
    tag: '생활용품',
    timeLeft: '4시간 45분',
    bidCount: 67,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 15,
    title: '닌텐도 스위치 OLED',
    price: '350,000',
    tag: '전자제품',
    timeLeft: '9시간 15분',
    bidCount: 85,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 16,
    title: '나이키 덩크 로우',
    price: '140,000',
    tag: '패션',
    timeLeft: '2일 4시간',
    bidCount: 156,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 17,
    title: '소니 WH-1000XM5 헤드폰',
    price: '380,000',
    tag: '전자제품',
    timeLeft: '6시간 22분',
    bidCount: 93,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 18,
    title: '루이비통 지갑',
    price: '520,000',
    tag: '패션',
    timeLeft: '1일 12시간',
    bidCount: 74,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 19,
    title: '삼성 갤럭시탭 S9',
    price: '890,000',
    tag: '전자제품',
    timeLeft: '14시간 5분',
    bidCount: 38,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 20,
    title: '비비안웨스트우드 목걸이',
    price: '250,000',
    tag: '패션',
    timeLeft: '8시간 40분',
    bidCount: 127,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 21,
    title: '골프 드라이버 테일러메이드',
    price: '480,000',
    tag: '스포츠',
    timeLeft: '3일 1시간',
    bidCount: 45,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 22,
    title: '이케아 소파 세트',
    price: '320,000',
    tag: '가구',
    timeLeft: '5시간 18분',
    bidCount: 89,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 23,
    title: 'LG 로보킹 청소기',
    price: '290,000',
    tag: '생활용품',
    timeLeft: '11시간 30분',
    bidCount: 56,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 24,
    title: '애플 워치 Series 9',
    price: '420,000',
    tag: '전자제품',
    timeLeft: '1일 7시간',
    bidCount: 167,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 25,
    title: '샤넬 향수 No.5',
    price: '180,000',
    tag: '패션',
    timeLeft: '9시간 12분',
    bidCount: 98,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 26,
    title: 'Xbox Series X',
    price: '540,000',
    tag: '전자제품',
    timeLeft: '16시간 45분',
    bidCount: 72,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 27,
    title: '윌슨 테니스 라켓',
    price: '150,000',
    tag: '스포츠',
    timeLeft: '2일 9시간',
    bidCount: 43,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 28,
    title: '한샘 책상',
    price: '240,000',
    tag: '가구',
    timeLeft: '7시간 8분',
    bidCount: 67,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 29,
    title: '필립스 에어프라이어',
    price: '180,000',
    tag: '생활용품',
    timeLeft: '13시간 25분',
    bidCount: 134,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 30,
    title: '레고 테크닉 람보르기니',
    price: '420,000',
    tag: '기타',
    timeLeft: '1일 15시간',
    bidCount: 87,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
];
