export const popularProducts = [
  {
    id: 1,
    title: '아이폰 14 Pro 256GB',
    price: '850,000',
    tag: '전자제품',
    timeLeft: '2시간 15분',
    bidCount: 75,
    image: 'https://invalid-url.com/no-image.jpg', // 테스트용 잘못된 URL
    liked: false,
  },
  {
    id: 2,
    title: '맥북 에어 M2 13인치',
    price: '1,200,000',
    tag: '전자제품',
    timeLeft: '5시간 30분',
    bidCount: 42,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 3,
    title: '나이키 에어조던 1 레트로',
    price: '180,000',
    tag: '패션',
    timeLeft: '1일 3시간',
    bidCount: 128,
    image: 'https://broken-image-url.com/fashion.jpg', // 테스트용 잘못된 URL
    liked: false,
  },
  {
    id: 4,
    title: '캐논 EOS R5 미러리스',
    price: '2,800,000',
    tag: '전자제품',
    timeLeft: '3시간 45분',
    bidCount: 23,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 5,
    title: '삼성 갤럭시 S23 Ultra',
    price: '950,000',
    tag: '전자제품',
    timeLeft: '6시간 20분',
    bidCount: 89,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 6,
    title: '에어팟 프로 2세대',
    price: '220,000',
    tag: '전자제품',
    timeLeft: '4시간 10분',
    bidCount: 156,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 7,
    title: '플레이스테이션 5',
    price: '450,000',
    tag: '전자제품',
    timeLeft: '8시간 30분',
    bidCount: 67,
    image: 'https://placehold.co/600x400',
    liked: false,
  },
  {
    id: 8,
    title: '아이패드 프로 11인치',
    price: '680,000',
    tag: '전자제품',
    timeLeft: '2일 5시간',
    bidCount: 34,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 9,
    title: '런닝화 아디다스 울트라부스트',
    price: '320,000',
    tag: '스포츠',
    timeLeft: '12시간 45분',
    bidCount: 91,
    image: 'https://no-image-found.com/sports.jpg', // 테스트용 잘못된 URL
    liked: false,
  },
  {
    id: 10,
    title: '원목 테이블 세트',
    price: '280,000',
    tag: '가구',
    timeLeft: '1일 8시간',
    bidCount: 203,
    image: 'https://missing-furniture-image.com/table.jpg', // 테스트용 잘못된 URL
    liked: false,
  },
  {
    id: 11,
    title: '브랜드 핸드백',
    price: '180,000',
    tag: '패션',
    timeLeft: '15시간 20분',
    bidCount: 45,
    image: 'https://placehold.co/600x400',
    liked: true,
  },
  {
    id: 12,
    title: '스마트 공기청정기',
    price: '420,000',
    tag: '생활용품',
    timeLeft: '3일 2시간',
    bidCount: 78,
    image: 'https://invalid-home-appliance.com/cleaner.jpg', // 테스트용 잘못된 URL
    liked: false,
  },
];
